### ISSUE TITLE
Add balances endpoint with support for more fiat than USD for balances

### ISSUE THREAD

**Issue by Uxio0** [gnosis/safe-client-gateway#133]
- fetch usd prices from safe-transaction service 
- use https://exchangeratesapi.io/ to fetch other exchange rates
- combine to return requested exchange rate

**Comment by jpalvarezl** [comment]
Should the clients send the fiat as a query parameter to the endpoint, or as part of the request, or do we have separate endpoints for each fiat? @rmeissner @Uxio0

**Comment by jpalvarezl** [comment]
I would think that from a caching perspective, maybe a query parameter makes sense, as we use the URLs as cache keys.

**Comment by jpalvarezl** [comment]
then we'd cache per fiat and per safe

**Comment by jpalvarezl** [comment]
On second thoughts, there is no argument to be made in terms of caching, as we cache the response from the transaction service, not the mapping done in the gateway.

**Comment by Uxio0** [comment]
> Should the clients send the fiat as a query parameter to the endpoint, or as part of the request, or do we have separate endpoints for each fiat? @rmeissner @Uxio0

I think as part of the url would be awesome, like `/balances/eur` or `/balances/usd`

**Comment by rmeissner** [comment]
We do cache the mapping done by the client gateway ;) 

and as this is a GET endpoint (would not see how POST makes sense here), the param would need to be in the URL (either path or query) ... as having it in the header also seems weird :thinking: 
Therefore I would go with what @Uxio0 proposed `/balances/<currency>` 
And if a currency is provided that we don't support I would throw a 422 with an appropriate message.

**Comment by jpalvarezl** [comment]
More details on the spec:

We will have two endpoints that return the same `Balance` structure:

```rust
pub struct Balance {
    pub token_info: TokenInfo,
    pub amount: String,
    pub fiat_amount: String,
}
```

`TokenInfo.type` will be hardcoded to `TokenType::Erc20` in the converter functions. This is the same structure used everywhere (just as a reminder) : 

```rust 
pub struct TokenInfo {
    #[serde(rename = "type")]
    pub token_type: TokenType,
    pub address: String,
    pub decimals: u64,
    pub symbol: String,
    pub name: String,
    pub logo_uri: Option<String>,
}
```

The 2 endpoints will be defined as: 

`/v1/safes/<safe_address>/balances/usd`
`/v1/safes/<safe_address>/balances/eur`

Please let me know if the struct is acceptable, @rmeissner . 

The transaction service returns additionally a field called `usd_conversion` which I skipped for now in the structs served by the gateway. If it's not necessary for the clients I would hide it, otherwise I would generify it to `fiat_conversion` where:
- for the `usd` endpoint: `fiat_conversion = usd_conversion`
- for the `eur` endpoint: `fiat_conversion = usd_conversion * usd_to_eur_conversion`

Assumption: `usd_to_eur_conversion` is provided by the link that @Uxio0 added to the description.

**Comment by Uxio0** [comment]
> Assumption: `usd_to_eur_conversion` is provided by the link that @Uxio0 added to the description.

Yes, but feel free to use any source you like, I didn't do too much research on that

**Comment by rmeissner** [comment]
The fiat currency should be a path parameter not a static route in my opinion

**Comment by rmeissner** [comment]
Should we make the fiat amount a float instead of a string?

**Comment by Uxio0** [comment]
> Should we make the fiat amount a float instead of a string?

Internally I would use a float, but remember that you need to provide it as a string when serializing again for iOs/Javascript/Android

**Comment by rmeissner** [comment]
Yes but that is for fiat values ... they are normally not in the 100s of billions :P

**Comment by jpalvarezl** [comment]
> Should we make the fiat amount a float instead of a string?

Numbers are tricky, I don't really know all the quirks of JS to give you an answer regarding that. I would just internally parse the stuff and serve it as a `String`, then consumer can decide.

**Comment by jpalvarezl** [comment]
Additional changes to take into account: https://github.com/gnosis/safe-transaction-service/issues/144
