### ISSUE TITLE
Some delay in getting lates tx details in gateway service after submitting a signature to the transaction service

### ISSUE THREAD

**Issue by sche** [gnosis/safe-client-gateway#161]
When confirming the tx with `transaction service`, then immediately requesting tx details with `gateway service`, the gateway service returns tx previous sate (1 owner signature less)

submitting signature to transaction service response time `2020-10-09 12:44:32.666000` --> status 201
requesting tx details from gateway response time `2020-10-09 12:44:32.786000` --> the submitted signature is missing
requesting tx details from gateway response time` 2020-10-09 12:44:35.390000` --> all signatures are there

Not sure it this is a gateway issue.

**Comment by jpalvarezl** [comment]
Due to the nature of the cache invalidation in the gateway, currently, the only way to invalidate caches for updates in transaction states is via web hooks. There is a delay associated with the web hook triggering and the communication time between the transaction service API and the gateway. 

Therefore, the behaviour of the gateway is expected. The feature request #162 should provide the means to invalidate caches immediately and supply the apps with the state updated  as required.
