### ISSUE TITLE
Unregister device for push notifications

### ISSUE THREAD

**Issue by Uxio0** [gnosis/safe-client-gateway#455]
**Endpoint URL**
`DELETE /v1/chains/<chain_id>/notifications/devices/<uuid>/safes/<address>/`

**Proposed payload**
No needed

**How it works**
It should relay the request to the corresponding transaction service

**Comment by fmrsabino** [comment]
Wondering about the path itself:

1) `DELETE /notifications/devices/{uuid}/safes/{chainId}/{address}/` (current proposal)
2)  `DELETE /notifications/devices/{uuid}/{chainId}/safes/{address}/`

in `1` we have the tuple `chainId-safeAddress` to identify a safe under `/safes` which makes a lot of sense specially in scenarios where the safe address is most of the times the same across different chains (given the same configuration)

In `2` we'd follow a more hierarchical approach where under the `/notifications/devices/{uuid}` resource: in order to identify the safe we'd have to know the `chainId` first and then under the `/safes` resource we'd identify the safe that we want with its address.

Nothing critical but wondering about the consistency of our endpoint structure so it matches how we address specific safes in different endpoints.

**Comment by jpalvarezl** [comment]
I just opened a ticket in order to address this: #457 

I think that the solution I've seen that most of us agree on being the nicest one would look something like:

`DELETE /v1/chains/<chain_id>/notifications/devices/<uuid>/safes/<address>`

I suppose we can wait until today's sync to somewhat "set this on stone" though :)

**Comment by Uxio0** [comment]
> Wondering about the path itself:
> 
> 1. `DELETE /notifications/devices/{uuid}/safes/{chainId}/{address}/` (current proposal)
> 2. `DELETE /notifications/devices/{uuid}/{chainId}/safes/{address}/`

Sorry, it was not the proposal, I just copied the transaction service endpoint, that's why I added `TBD` 😉
