### ISSUE TITLE
Change println! to logs with rocket

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-client-gateway#50]

**Comment by jpalvarezl** [comment]
It seems that log level is defined in the .env file: https://github.com/gnosis/safe-client-gateway/pull/43

**Comment by rmeissner** [comment]
Maybe we should take a look at https://github.com/rust-lang/log

**Comment by rmeissner** [comment]
nick recommends `dbk!` as a replacement for `print!`

**Comment by jpalvarezl** [comment]
Hmm this seems to be a wrapper for `println!()` with the `{:?}` matcher implied :/ At least that's my understanding of the documentation: https://doc.rust-lang.org/std/macro.dbg.html

**Comment by rmeissner** [comment]
Probably https://docs.rs/log/0.4.11/log/macro.debug.html is more what we want

**Comment by jpalvarezl** [comment]
This one is fairly popular: https://crates.io/crates/pretty_env_logger ? Or you don't want to add a new dependency?

**Comment by rmeissner** [comment]
We can add this, but it is not required for this issue. This issue is about replacing the print macro with something more inline with proper logging. Therefore the first step would be to use the debug! Macro instead of print!. Once this is changed we can see that logging framework we use to improve the output and filter the logging based on the environment. I am fine with any of the loggers, as I didn't do any comparison between the different loggers.

**Comment by jpalvarezl** [comment]
So let's start at the beginning then :)

**Comment by rmeissner** [comment]
Ohh never mind we need an implementation to use the facade ... I am fine starting with a simple one. Would be nice to add the log level to the env file and write in the readme the different options (or a link to somewhere where the options are mentioned)
