### ISSUE TITLE
Add safeTxHash to the history/queue summaries

### ISSUE THREAD

**Issue by katspaugh** [gnosis/safe-client-gateway#786]
## Context

We're using `safeTxHash` as an internal id on the client side. `safeTxHash` works well for us because it's not changing throughout the life cycle of a transaction.

 * to track things like Pending Status
 * to open individual transactions from a URL (aka tx deep-linking)

## Problem
`safeTxHash` is present in the `detailedExecutionInfo` when fetching the details of an individual tx, but not accessible in the list (History and Queue).

Currently, we're relying on a dirty hack to check if a tx is pending in the list (by parsing the id field 🙈).

## Feature request
Please add `safeTxHash` to the History and Queue endpoints. It should be on the top level of each `transaction` item, alongside the `id` field.

E.g.
```
{
  "id": "multisig_0x5f9ee776B85f1aFF123f935C48C528D00a62B0ad_0x204bd8ec34dad230927a095763e98844ca687e6aebc2148b38a8edcb8ca35b16",
  "safeTxHash": "0x204bd8ec34dad230927a095763e98844ca687e6aebc2148b38a8edcb8ca35b16",
  "timestamp": 1641296587000,
  ...
}
```
<img width="898" alt="Screenshot 2022-01-28 at 13 26 42" src="https://user-images.githubusercontent.com/381895/151546759-7250894c-b171-4261-bc87-ce79d88bb816.png">

**Comment by katspaugh** [comment]
@iamacook please correct me if I'm wrong – we've discovered that the id is changing throughout the life-cycle of a single transaction, whereas the safeTxHash remains the same. Hence we picked the safeTxHash.

**Comment by rmeissner** [comment]
That might be problematic for deep links that should be valid "forever", but why would this be problematic for tracking the pending state?

I think we should align here what you want to do and also explain the functionality of the id.

**Comment by iamacook** [comment]
If I remember correctly, the `safeTxHash` was chosen because of the bug we encountered regarding [transactions temporarily being `"CANCELLED"`](https://github.com/gnosis/safe-client-gateway/issues/37). Retrieving transactions by their `safeTxHash` did/does not seem to return `"CANCELLED"` as often.

Upon executing a transaction, the `txStatus` was being locally overwritten to `"PENDING"` and then updated according to the CGW. Hence, it was temporarily `"CANCELLED"` in the UI.

As we are polling for summaries, by adding the `safeTxHash` there, we would not need to parse the `txId` to determine if the transaction was successful. If the `txId` doesn't change during the lifecycle of a transaction, we could indeed rely on that instead for deeplinking/status tracking.

I [altered the way pending statuses are tracked](https://github.com/gnosis/safe-react/pull/3360) this week so that the state isn't mutated. It would relatively easy to pivot to using the `txId` instead as we now store a hashmap (`{ [chainId]: Set<safeTxHash> }`) of pending transactions.

There was a [mobile kick-off](https://docs.google.com/document/d/1aoW-HZDeQCRpMVMaHOUZQZyBNMWcqCo51IEkq3zEBlE) this week in which we discussed using the `txId` as all transactions have them compared to the `safeTxHash`. There is an [open issue to improve the deeplinking](https://github.com/gnosis/safe-react/issues/3296) where this would be considered.

If the `txId` is persistent, I don't see a reason for our reliance on the `safeTxHash` now we have altered the status tracking. My only question would be, if are we alright with the long URLs or could we minify them in some way? Although, that is more related to deeplinking.

**Comment by katspaugh** [comment]
URL length doesn't matter IMHO.

I'm closing this, then. We'll use the id for both deep linking and the local pending status. Will reopen in case we notice problems with the id again.

**Comment by iamacook** [comment]
@rmeissner, can you confirm whether the `txId` remains the same from transaction creation, through execution to success (for all transaction types)? I'll update the deeplinking v2/create a status tracking tweak issue accordingly.

**Comment by rmeissner** [comment]
@iamacook not sure I understand your question. We currently to not allow to fetch creation information for a Safe via the client gateway. If this is required please create a new issue and link to the epic for which this is required, so that we are aware of the flow.

**Comment by iamacook** [comment]
Thank you for the clarification. Since my question, I have [made the required alterations](https://github.com/gnosis/safe-react/pull/3410) to not use the `safeTxHash` anymore.
